- src/main/kotlin/com/msg/gauth/domain/client/presentation/ClientController.kt
- src/main/kotlin/com/msg/gauth/domain/client/repository/ClientRepository.kt
- src/main/kotlin/com/msg/gauth/domain/client/services/UpdateAnyClientService.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
어드민 서비스 수정 api
어드민 서비스 수정
서비스명 이름을 일단 updateAnyClientService로 짓긴했는데 (updateClientService가 이미 있어서) 더 좋은 이름이 있으면 추천해주세요..
> 어드민 서비스 수정 api

- src/main/kotlin/com/msg/gauth/domain/auth/services/SignUpService.kt
- src/main/kotlin/com/msg/gauth/domain/user/User.kt
- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptTeacherReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/services/AcceptTeacherSignUpService.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
회원가입한 선생님 수락하기
수락 api 서비스를 만들었습니다.
> 회원가입한 선생님 수락하기

- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
* 이미지 업로드에서 500터짐
* 시큐리티 설정 문제긴 했는데 gauth 본섭에서도 고쳐지는지는 모르겠음
> 🔀 ::98 - 이미지 업로드가 안되던 버그

- src/main/kotlin/com/msg/gauth/domain/oauth/presentation/OauthController.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/OauthCodeService.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
* 아니 프론트가 급발진해서 main에 박아버림;;
* accessToken으로 code발급받는 API개발
@jjaejjae12
> 아니 프론트가 상의도 없이 accessToken으로 code발급받는 API 만들라함;;

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
> 🔀 :: 109 ci/cd

- src/main/kotlin/com/msg/gauth/domain/email/services/MailSendService.kt
- src/main/kotlin/com/msg/gauth/global/mail/MailConfig.kt
- src/main/kotlin/com/msg/gauth/global/thymeleaf/ThymeleafConfig.kt
- src/main/resources/templates/mail-template.html
> 🔀 :: 이메일 템플릿 오류

- src/main/kotlin/com/msg/gauth/domain/admin/services/ExcelParsingService.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
* 엑셀 파싱하는데 쿼리가 많이 나감
* in을 사용해서 조회하고 수정하게끔 변경
* 더 최적화 시킬 수 있는 부분있을거 같으면 코멘트 달아주세요
> 🔀 :: 117 -  쿼리 줄이기

- scaffold.py
- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/GetMyRolesResDto.kt
- src/main/kotlin/com/msg/gauth/domain/user/services/GetMyRolesService.kt
> 🔀 :: 현재 본인의 Role을 가져오는 API

- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/SinglePendingListResDto.kt
response에 id가 안담겨있어서 넣어서 보냈습니다..
> :sparkles: responseDto에 id 추가

- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
- src/main/kotlin/com/msg/gauth/domain/user/services/AcceptedUserService.kt
queryString에서 키워드로 검색하는 부분을 nullable로 변경하였습니다
> 126 user list keyword nullable

- src/main/kotlin/com/msg/gauth/domain/auth/services/RefreshService.kt
- src/main/kotlin/com/msg/gauth/domain/auth/services/SignInService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/OauthRefreshService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/OauthTokenService.kt
- src/main/kotlin/com/msg/gauth/global/security/jwt/JwtTokenProvider.kt
- src/main/kotlin/com/msg/gauth/global/security/jwt/OauthTokenProvider.kt
oauth provider 분리, provider사용하는 서비스 살짝쿵 리팩터링
> 131 jwt provider oauth gauth

- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
> :wastebasket: acceptTeacher, Student deprecated

- src/main/kotlin/com/msg/gauth/domain/oauth/presentation/OauthController.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/presentation/dto/request/OauthTokenRequestDto.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/presentation/dto/response/OauthTokenResponseDto.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/GenerateOauthCodeService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/GenerateOauthTokenService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/OauthTokenService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/services/RefreshOauthTokenService.kt
* oauth토큰을 발급시에 oauth 코드 지우기
* oauth토큰을 발급시에 oauth 코드 지우는 로직 추가
* 서비스 이름도 컨벤션 적용..
> 🔀 :: 108 - oauth토큰 발급시 oauth코드 지우기

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/DependencyVersions.kt
- buildSrc/src/main/kotlin/PluginVersion.kt
buildSrc에 Dependency들을 옮겨 gradle에 적용했습니다.
buildSrc모듈 추가, Dependencies, DependencyVersion, PluginVersion obj
> :art: :: buildSrc 적용

- .github/CODEOWNERS
> 🔀 :: 84 - codeowners 세팅

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/DependencyVersions.kt
- buildSrc/src/main/kotlin/PluginVersion.kt
- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/services/GetAcceptedUsersService.kt
- src/main/kotlin/com/msg/gauth/global/querydsl/QuerydslConfig.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
가입된 유저 검색 서비스를 리팩터링 해보았습니다.
1. pageable 대신 page, size를 인자로 받고 Page를 리턴하도록 변경했습니다.
2. filter를 사용해서 다중 if문을 줄였습니다. 예시로 grade == 0일때는 뒤의 연산(it.grade == grade)을 수행하지 않고 넘어가도록 코드를 작성했습니다.
> 가입된 유저 검색 서비스 리팩터링

- src/main/kotlin/com/msg/gauth/GauthBackendApplication.kt
- src/main/kotlin/com/msg/gauth/domain/auth/services/SignupImageUploadService.kt
- src/main/kotlin/com/msg/gauth/domain/user/services/UploadProfileService.kt
- src/main/kotlin/com/msg/gauth/global/config/jackson/JacksonConfig.kt
- src/main/kotlin/com/msg/gauth/global/config/querydsl/QuerydslConfig.kt
- src/main/kotlin/com/msg/gauth/global/config/thymeleaf/ThymeleafConfig.kt
- src/main/kotlin/com/msg/gauth/global/config/web/WebMvcConfig.kt
- src/main/kotlin/com/msg/gauth/global/filter/ExceptionFilter.kt
- src/main/kotlin/com/msg/gauth/global/filter/JwtTokenFilter.kt
- src/main/kotlin/com/msg/gauth/global/security/config/FilterConfig.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/aws/s3/AwsS3Config.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/aws/s3/S3Util.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/mail/MailConfig.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/mail/properties/MailProperties.kt
> :art: :: global package 구조 개선

- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
querydsl로 유저 다중 검색을 booleanBuilder를 사용했었는데 Expression을
사용하도록 리팩터링 해보았습니다.
customUserRepositoryImpl searchUser 메서드 리팩터링
> :recycle: :: booleanExpression 사용

- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptedUserRequest.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/services/GetAcceptedUsersService.kt
수락된 유저 검색에 UserRole로 검색할 수 있는 조건추가
when으로 UserRole이 Role_Student가 아니라면 UserRole로 DB에서 검색하도록 했습니다
@baekteun 기획미스 뭔데요
> 수락된 유저 검색에 UserRole로 검색

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/todo.yml
* 이슈 탬플릿을 작성합니다.
* bug 탬플릿
* todo (feature) 탬플릿
~~from gcms~~
> 🔀  :: 87 - 이슈 탬플릿

- src/main/kotlin/com/msg/gauth/global/filter/RequestLogFilter.kt
- src/main/kotlin/com/msg/gauth/global/security/config/FilterConfig.kt
* 불미스러운 일에 대비한 요청 로깅
* 모든 request를 로깅할 수 있는 필터 추가
> 🔀 :: 164 - gauth에 모든 요청을 로깅하는 필터 추가

- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
PacthMapping "oauth/code" -> "oauth/token"
> 🔀 라우팅 오타 수정

- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
> delete :: @EnabledWebSecurity annotation

- src/main/kotlin/com/msg/gauth/global/security/CustomAccessDeniedHandler.kt
- src/main/kotlin/com/msg/gauth/global/security/CustomAuthenticationEntryPoint.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
AccessDeniedHandler를 구현한 CustomAccessDeniedHandler가 없어서 만들었ㅇ어요
> 🔀 CustomAccessDeniedHandler 작성

- src/main/kotlin/com/msg/gauth/domain/auth/repository/MinuteSignInCountRepository.kt
- src/main/kotlin/com/msg/gauth/domain/auth/repository/RefreshTokenRepository.kt
- src/main/kotlin/com/msg/gauth/domain/auth/repository/SecondSignInCountRepository.kt
- src/main/kotlin/com/msg/gauth/domain/auth/repository/TempSignInBanRepository.kt
- src/main/kotlin/com/msg/gauth/domain/auth/service/RefreshService.kt
- src/main/kotlin/com/msg/gauth/domain/auth/service/SignInService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/repository/MinuteOAuthSignInCountRepository.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/repository/OauthCodeRepository.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/repository/OauthRefreshTokenRepository.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/repository/SecondOAuthSignInCountRepository.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/repository/TempOAuthSignInBanRepository.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/service/GenerateOauthCodeService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/service/GenerateOauthTokenService.kt
- src/main/kotlin/com/msg/gauth/domain/oauth/service/RefreshOauthTokenService.kt
- src/main/kotlin/com/msg/gauth/domain/user/util/TempUserUtil.kt
- src/main/kotlin/com/msg/gauth/domain/user/util/UserUtil.kt
- src/main/kotlin/com/msg/gauth/global/util/count/auth/MinuteSignInCount.kt
- src/main/kotlin/com/msg/gauth/global/util/count/auth/RefreshToken.kt
- src/main/kotlin/com/msg/gauth/global/util/count/auth/SecondSignInCount.kt
- src/main/kotlin/com/msg/gauth/global/util/count/auth/TempSignInBan.kt
- src/main/kotlin/com/msg/gauth/global/util/count/auth/util/TooManyRequestValidUtil.kt
- src/main/kotlin/com/msg/gauth/global/util/count/oauth/MinuteOAuthSignInCount.kt
- src/main/kotlin/com/msg/gauth/global/util/count/oauth/OauthCode.kt
- src/main/kotlin/com/msg/gauth/global/util/count/oauth/OauthRefreshToken.kt
- src/main/kotlin/com/msg/gauth/global/util/count/oauth/SecondOAuthSignInCount.kt
- src/main/kotlin/com/msg/gauth/global/util/count/oauth/TempOAuthSignInBan.kt
- src/main/kotlin/com/msg/gauth/global/util/count/oauth/util/TooManyOAuthRequestValidUtil.kt
count util 패키지 global로 이동
GenerateOauthCodeService 비정상 공백 삭제
[GenrateOauthCodeService 비정상 공백 이슈 해결](https://github.com/GSM-MSG/GAuth-BackEnd/issues/185)
> 189 count package

- src/main/kotlin/com/msg/gauth/domain/client/repository/ClientRepository.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/GetAllClientsService.kt
GetAllClientService public scope 서비스만 가져오도록 수정했습니다.
> chore :: PUBLIC scope service

- src/main/kotlin/com/msg/gauth/domain/client/Client.kt
columnDefinition 테이블 생성 쿼리문에 끝맺음이 안되어있던 오타를 수정하였습니다
> :bug: :: ' 끝맺음 해주기

- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
마이페이지 response에 service_scope가 빠져있던걸 추가해주었습니다
> 🔀 :: Mypage response에 service_scope추가

- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
BooleanExpression 조건식이 null일 때 유저 전체조회 대신 학생만 조회하도록 코드를 손봤습니다
메인브랜치에아무일도없었습니다신경쓰지마세요
> 🔀 :: expression이 null일때 전체 조회에서 학생 조회로 변경

- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
쿼리DSL if문 없애고 expression을 where함수 안에 통합시켰습니다
> 🔀 :: 학생조회 QueryDSL return문 통합

- src/main/kotlin/com/msg/gauth/domain/client/Client.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/ClientRegisterReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/ClientUpdateReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/response/ClientDetailResDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/response/ClientRegisterResDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/response/ClientResDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/response/SingleClientResDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/UpdateAnyClientService.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/UpdateClientService.kt
서비스를 등록할 때 이미지url도 입력받을 있도록 변경하였습니다
클라이언트의 정보를 받는 request에 url 필드를 추가하였고
클라이언트의 정보를 반환하는 response에 url 필드를 추가하였고
클라이언트 엔티티 컬럼에 ImgUrl필드를 추가했읍니다
> 🔀 207 add img url on service add request

- src/main/kotlin/com/msg/gauth/domain/client/presentation/ClientController.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/ClientRegisterReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/ClientUpdateReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/RegisterClientService.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/UpdateAnyClientService.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/UpdateClientService.kt
- src/main/kotlin/com/msg/gauth/domain/image/presentation/ImageController.kt
- src/main/kotlin/com/msg/gauth/domain/image/presentation/dto/response/UploadImageResDto.kt
- src/main/kotlin/com/msg/gauth/domain/image/service/DeleteImageService.kt
- src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
- src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
- src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileService.kt
- src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileURLService.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
MultipartFile을 받아서 서비스의 이미지를 업로드하고 수정하는 코드를 추가했습니다
이미지 업로드 api 나누고싶어지는순간이었습니다
> 🔀 209 client image upload issue

- src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
조건식이 True 때 조건을 통과시켜야 하는데 반대로 되어 있었습니다
@baekteun 형을 믿었는데...
> :bug: :: if 조건식이 반대로 되어있었던 버그 수정

- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
마이페이지 response에 클라이언트 이미지 url을 추가하였습니다
서무지 독재정부는 물러나라
> 🔀 :: 마이페이지 response에 클라 이미지 url 추가

- src/main/kotlin/com/msg/gauth/global/filter/ExceptionFilter.kt
- src/main/kotlin/com/msg/gauth/global/filter/RequestLogFilter.kt
핸들링되지 않은 에러가 발생했을 때 에러 원인을 로깅할 수 있도록 바꾸었습니다
ExceptionFilter에서 throw한 Exception을 RequestLogFilter에서 위임받아 에러 원인을 로깅하도록 했습니다
> 🔀 :: 핸들링 되지 않은 에러 발생 시 에러 원인 로깅

- src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordInitReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/SignInRequestDto.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/SignUpRequestDto.kt
선생님 학교용 이메일에 .이 포함되어 있는 경우가 확인되어 정규식에 .를 추가합니다
회원가입과 로그인시 정규식에 ```.```을 추가했습니다
> add :: 정규식 허용문자 중 .추가

- src/main/kotlin/com/msg/gauth/domain/client/Client.kt
- src/main/kotlin/com/msg/gauth/domain/client/repository/CustomClientRepositoryImpl.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/DeleteClientsService.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/RegisterClientService.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/UpdateAnyClientService.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/UpdateClientService.kt
- src/main/kotlin/com/msg/gauth/domain/image/presentation/ImageController.kt
- src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
- src/main/kotlin/com/msg/gauth/domain/user/service/AcceptStudentSignUpService.kt
- src/main/kotlin/com/msg/gauth/domain/user/service/AcceptUserSignUpService.kt
- src/main/kotlin/com/msg/gauth/global/exception/handler/GlobalExceptionHandler.kt
- src/main/kotlin/com/msg/gauth/global/filter/ExceptionFilter.kt
- src/main/kotlin/com/msg/gauth/global/filter/RequestLogFilter.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/mail/MailConfig.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/mail/properties/MailProperties.kt
코드를 읽는 중에 불필요하거나 쓰이지 않는 import문을 발견하여 삭제하였습니다.
각각의 코드들을 보면서 쓰이지 않지만 삭제되지않은 import를 삭제하였습니다
> deleted::불필요한 import문 삭제

- src/main/kotlin/com/msg/gauth/domain/health/presentation/HealthCheckController.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
health check를 하는 api를 만들었습니다.
domain에 health라는 패키지를 만들어 controller에 healthCheck메서드로 200을 보내주는 메서드를 만들어주었습니다
> 🔀 ::healthCheck api 추가

- src/main/kotlin/com/msg/gauth/domain/auth/handler/AuthEventHandler.kt
회원가입 웹훅 디자인하기
url을 추가하여 글씨를 누르면 해당 url로 이동
> 🔀::emded에 url추가

- appspec.yml
CD 구축을 위한 appspec.yml을 추가했습니다다
패키지 루트 디렉토리에 appspec.yml 추가
> :twisted_rightwards_arrows: :: appspec.yml 추가

- deploy.sh
CD 구축을 위한 deploy.sh 파일을 추가하였습니다
deploy.sh 파일 추가
> :twisted_rightwards_arrows: :: deploy.sh 파일 추가

- src/main/resources/application.yml
yml에 있는 DB 설정들을 환경변수로 관리하도록 하였습니다
DB Driver와 Platform을 환경변수로 관리하도록 함
데이터베이스에 접근할 때 사용하는 url을 mariaDB에서 MySQL로 변경하였습니다
아니 저희 RDS로 Mysql쓰는데 설정파일이 MariaDB면 원래 동작이 안되야하는데 왜 지금까지 됐던거죠
> 🔀 :: 250 DB Driver class와 platform 환경변수로 관리

- .github/workflows/Gauth-CD.yml
Gauth CD가 구축되어 있지 않기 때문에, CD를 구축하였습니다.
Gauth CD용 yml 파일을 생성함.
workflows 폴더에 Gauth-CD.yml 파일 생성하였습니다.
> 🔀 create ::  Gauth-CD.yml 파일 생성

- .github/workflows/Gauth-CD.yml
Gauth-CD.yml 파일을 수정하였습니다.
55, 57번째 줄에 오타가 있어 수정하였습니다.
55, 57번째 줄에 오타가 있어 수정하였습니다.
> 🔀 Update :: Gauth-CD.yml

- .github/CODEOWNERS
저를 코드리뷰어에 추가하였습니다
* CODEOWNERS 수정
> 🔀 :: CODEOWNERS에 저를 추가

- deploy.sh
deploy.sh 파일을 수정하였습니다. 
&앞에 띄어쓰기를 추가하였습니다.
> 🔀 :: update deploy.sh

- deploy.sh
deploy.sh 파일을 수정하였습니다.
PID 값을 가져올때 -t 옵션을 추가햐여 해당 포트를 사용하는 PID 값만 출력하도록 하였습니다.
PID 값 가져올때 -t 옵션 추가.
> 🔀 update :: deploy.sh

- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
명세서에 있는 빠트린 uri pattern들 추가해주었씁니다
살리고싶으면빨리어프루브누르세요
> add :: broken uri patterns

- src/main/kotlin/com/msg/gauth/domain/user/User.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRoleRepository.kt
- src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
- src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetails.kt
- src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetailsService.kt
user role 프로퍼티를 롤백 했습니다 다시 양방향 매핑이 되도록 하였습니다
> 🔀 :: 280 User의 UserRole 프로퍼티 롤백

- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
user list api를 인증된 권한이라면 모두 조회할 수 있도록 변경하겠습니다
security config url pattern 변경
> 🔀 :: user list 인증된 권한은 조회할 수 있도록 변경

- src/main/kotlin/com/msg/gauth/domain/admin/service/ExcelParsingService.kt
엑셀로 유저 수락 시 유저 상태도 CREATED로 함께 변경되던 부분이 삭제되어 다시 추가해주었습니다
user의 인스턴스를 만들 때 state를 CREATED로 변경하도록 하였습니다
> 🔀  :: set user status created

- src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
자신의 프로필 정보를 반환할 때 유저의 id까지 반환하도록 변경하였습니다
MyProfileResDto에 id: Long 프로퍼티 추가
MyProfileResDto 생성자 가시성 개편
> 🔀  :: my profile response dto에 id추가

- src/main/kotlin/com/msg/gauth/domain/client/service/DelegateOwnerService.kt
위임자의 권한을 검사하는 로직을 수정하였습니다.
* if문 조건 수정
> 🔀 :: 서비스 위임자 권한 로직 수정

- src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
유저 리스트 시 인자가 들어오는 조건에 따라 동적으로 정렬이 발생하도록 하였습니다
* 학년을 검색 조건으로 추가하였을 경우 -> 반, 번호 순으로 정렬
* 반을 검색 조건으로 추가하였을 경우 -> 학년, 번호 순으로 정렬
* 학년과 반 모두를 검색 조건으로 추가하였을 경우 -> 번호 순으로 정렬
* 아무것도 하지 않았을 경우 -> 학년, 반, 번호, 순으로 정렬
> 🔀  :: 유저 리스트 동적인 정렬 처리

- .github/workflows/Gauth-CD.yml
- .github/workflows/ci.yml
application yml 덮어쓰기 job 추가
cd 워크플로에서 github secret에 저장된 application.yml을 가져와 덮어쓰기 수행하는 job을 새로 추가했습니다
> 🔀 :: application.yml overwrite job

- src/main/kotlin/com/msg/gauth/domain/auth/exception/PasswordAndNewPasswordSameException.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/InitPasswordRequestDto.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/UpdatePasswordRequestDto.kt
- src/main/kotlin/com/msg/gauth/domain/auth/service/InitPasswordService.kt
- src/main/kotlin/com/msg/gauth/domain/auth/service/UpdatePasswordService.kt
- src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
디자인에 기존 비밀번호와 새 비밀번호가 일치하면 안된다는 디자인이 있어 추가하였습니다
* ErrorCode 추가
* PasswordAndNewPasswordSameException 추가
* 서비스에 검사 로직 추가
> 🔀 :: 기존 비밀번호와 새 비밀번호와 다른지 검사하는 로직 

- src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
- src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpImageUploadService.kt
- src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
- src/main/kotlin/com/msg/gauth/global/thirdparty/aws/s3/S3Util.kt
회원가입할 때 이미지 업로드시에 확장자를 검사하는 로직이 없어 추가하였습니다
* signUpImageUploadService에 확장자 검사 로직 추가
* updatePassword에 유효성 검사 어노테이션 추가
> 🔀 :: 회원가입시 이미지 확장자 검사 로직

- appspec.yml
- deploy.sh
파일 경로를 수정하여 s3에서 가져온 빌드된 프로젝트를 실행하도록 했습니다
> 🔀 :: CD 스크립트 수정

- src/main/kotlin/com/msg/gauth/domain/email/service/SendMailService.kt
> PR을 하게 된 문제상황, 배경 및 개요에 대해서 작성해주세요!
> 이메일 인증시 url이 옛날 도메인으로 되어있어 변경하였습니다.
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
Resolves: #316 
> createMailTemplate의 url을 현재 서버 주소로 변경하였습니다.
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!
> 🔀 :: 이메일 인증 url 변경

- src/main/kotlin/com/msg/gauth/domain/client/Client.kt
- src/main/kotlin/com/msg/gauth/domain/client/Coworker.kt
- src/main/kotlin/com/msg/gauth/domain/client/exception/AlreadyExistCoworkerException.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/ClientController.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/AddCoworkerReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/CoworkerAddReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/repository/CoworkerRepository.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/AddCoworkerService.kt
- src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
서비스에 오너뿐만 아니라 공동작업자들을 등록할 수 있게 하기 위한 api를 개발했습니다
Resolves: #324 
Coworker를 만들어 client와 user와 매핑하였습니다. 또한 addCoworker를 만들어 만들어져있는 서비스에 공동작업자를 추가할 수 있게 만들었습니다
> 🔀 :: 서비스의 공동작업자 추가

- src/main/kotlin/com/msg/gauth/domain/client/exception/CoworkerNotFoundException.kt
- src/main/kotlin/com/msg/gauth/domain/client/exception/NotFoundCoworkerException.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/ClientController.kt
- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/request/DeleteCoworkerReqDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/repository/CoworkerRepository.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/DeleteCoworkerService.kt
- src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
등록되어있는 공동작업자를 삭제할 수 있는 api를 만들었어요
Resolves: #328 
deleteCoworker api를 만들고 커스텀 예외를 만들어서 예외처리를 하였어요
> 🔀 :: 등록된 공동작업자 삭제

- src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/response/ClientRegisterResDto.kt
- src/main/kotlin/com/msg/gauth/domain/client/service/RegisterClientService.kt
클라이언트에서 서비스 등록할때 id까지 같이 준다면 공동작업자 등록할 때 편하기 때문에 추가하였습니다
Resolves: #333 
responseDto에 id를 추가하였습니다
> 🔀 :: 서비스 등록 api의 response에 id를 추가

- src/main/kotlin/com/msg/gauth/domain/auth/exception/AlreadyExistUserException.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
- src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/SignUpV2RequestDto.kt
- src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpMemberV2Service.kt
- src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
api 버저닝을 통해 학번과 이름을 받아 회원가입을 할 수 있는 api를 추가하였습니다
Resolves: #337 
SignUpMemberV2를 추가하였고 v2회원가입에는 학번과 이름을 동시에 받는 api로 구현하였습니다
> 🔀 :: 학번과 이름을 받는 회원가입
