GSM-MSG/GAuth-BackEnd

src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordInitReqDto.kt, src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/SignupRequestDto.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/PasswordChangeReqDto.kt
* 패스워드 정규식 변경
* 정규식을 좀 더 간결하게 만들고 생략된 특문 추가
=> 패스워드 정규식 수정

src/main/kotlin/com/msg/gauth/global/web/WebMvcConfig.kt
프론트 개발섭의 cors를 허용해줍니다
WebMvcConfig에서 cors에 https://dev-gauth-frontend.vercel.app 해당 url을 허어요옹하압니이다아
=> 🔀 :: 프론트 개발섭의 cors 허용

src/main/kotlin/com/msg/gauth/domain/user/User.kt, src/main/kotlin/com/msg/gauth/domain/user/enums/UserRole.kt, src/main/kotlin/com/msg/gauth/domain/user/services/AcceptTeacherSignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/services/AcceptUserSignUpService.kt
유저 회원가입 수락에 졸업생 수락 기능 추가 🔨
user의 업데이트 함수중 Teacher, Graduate의 업데이트 함수를 
updateTeacher updateGraduate로 메서드 명을 변경했습니다. ✍️
user entity update Method name, AcceptUserSignUpService
=> 유저 회원가입 수락에 졸업생 수락 기능 추가

src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/SingleAcceptedUserResDto.kt
수락된 유저 리스트 api의 Response DTO 변수 중 학년, 반, 번호를 nullable로 변경하였습니다
선생님과 졸업생을 반환하는 새로운 기능이 생기면서 가지고 있지 않는 학년, 반, 번호를 null로 담아야 하기 때문입니다
=> 🔀 ::Response DTO 학년/반/번호 nullable 변수로 변경

src/main/kotlin/com/msg/gauth/domain/client/presentation/ClientController.kt, src/main/kotlin/com/msg/gauth/domain/client/repository/ClientRepository.kt, src/main/kotlin/com/msg/gauth/domain/client/repository/CustomClientRepository.kt, src/main/kotlin/com/msg/gauth/domain/client/repository/CustomClientRepositoryImpl.kt, src/main/kotlin/com/msg/gauth/domain/client/service/DeleteClientsService.kt, src/main/kotlin/com/msg/gauth/domain/client/service/DeleteSeveralClientService.kt, src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
유저가 등록한 서비스를 여러 개 삭제할 수 있는 api 작성
=> 🔀 172 delete enrolled service

src/main/kotlin/com/msg/gauth/domain/auth/service/SignInService.kt, src/main/kotlin/com/msg/gauth/domain/oauth/service/GenerateOauthCodeService.kt, src/main/kotlin/com/msg/gauth/domain/user/util/TempUserUtil.kt
* 계속 누적하니까 뜬금없이 로그인 정지 당하는 경우가 많음
* 로그인 성공시 틀린 횟수 초기화
* OAuth 로그인 성공시 틀린 횟수 초기화 
* 로그인 로직에서 pending상태를 검증하게 수정
=> 🔀  :: 180 - 로그인 성공시 틀린 횟수 초기화

src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt, src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileService.kt
유저 이름이 null이 되는 이유가 업로드에서 user를 생성할 때 name을 넣어주지 않아서입니다. ㅠㅠ
그래서 검색이 안되는 이유가 각 유저마다 name이 null인 유저들이 있어서 인 것 같습니다. 
수정했습니다.
=> user 이름이 null이 되는 현상이 이미지 업로드 때문인 것 같습니다.

src/main/kotlin/com/msg/gauth/domain/auth/service/RefreshService.kt, src/main/kotlin/com/msg/gauth/domain/client/Client.kt
ServiceScope columnDefinition에 DEFAULT 옵션 추가
=> add :: column definition 추가

src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptedUserRequest.kt
유저 리스트를 전체 조회할 때 원래 정해진 값을 파라미터에 넣어 보내야 전체 검색이 되었는데 파라미터를 보내지 않으면 전체 조회가 되도록 RequestParam의 required 속성을 false로 바꾸어주었습니다
=> :art: :: requestParam null 허용

src/main/resources/application.yml
Multipart Request의 용량 제한을 1MB에서 5MB로 증대시켰습니다
=> 🔀 :: multipart request 용량 5MB로 증대

src/main/kotlin/com/msg/gauth/domain/auth/service/RefreshService.kt, src/main/kotlin/com/msg/gauth/domain/oauth/OauthCode.kt, src/main/kotlin/com/msg/gauth/domain/oauth/repository/OauthCodeRepository.kt, src/main/kotlin/com/msg/gauth/domain/oauth/service/GenerateOauthCodeService.kt, src/main/kotlin/com/msg/gauth/domain/oauth/service/RefreshOauthTokenService.kt, src/main/kotlin/com/msg/gauth/global/filter/JwtTokenFilter.kt, src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt, src/main/kotlin/com/msg/gauth/global/security/config/FilterConfig.kt, src/main/kotlin/com/msg/gauth/global/security/jwt/JwtTokenProvider.kt, src/main/kotlin/com/msg/gauth/global/security/jwt/OauthTokenProvider.kt, src/main/kotlin/com/msg/gauth/global/security/jwt/TokenParser.kt
`OAuthTokenProvider`, `JwtTokenProvider`는 parseToken()이라는 토큰을 파싱하는
과정의 **공통 로직의 보일러 플레이트코드**를 가지고 있었습니다.
TokenParser 클래스로 **책임을 분리함**으로써 문제를 해결했습니다.
+ 집나간 OauthCode 엔티티 클래스를 다시 불러들였습니다.
- TokenParser 클래스로 parseToken 작업 처리
- RefreshOAuthCodeService tokenParser 의존
- SignInService tokenParser 의존
```kt
@Component
class TokenParser(
private val jwtProperties: JwtProperties,
private val authDetailsService: AuthDetailsService
) {
fun parseToken(token: String): String? =
if (token.startsWith(JwtTokenProvider.TOKEN_PREFIX)) token.replace(JwtTokenProvider.TOKEN_PREFIX, "") else null
fun exactEmailFromRefreshToken(refresh: String): String {
return getTokenSubject(refresh, jwtProperties.refreshSecret)
}
fun exactEmailFromOauthRefreshToken(refresh: String): String =
getTokenSubject(refresh, …
```
=> refactor :: OAuthTokenProvider, JwtTokenProvider 공통 parseToken 로직 분리

src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
어드민 API중 하나인 학생 전체 조회 기능이 데이터베이스의 PENDING 상태인 유저의 역할이 ROLE_STUDENT로 부여되어 학년 반 번호가 존재하지 않는 로우가 같이 조회되어 NPE가 발생하는 문제가 생겼습니다. 따라서 CREATED 상태의 STUDENT만 조회하도록 했습니다
학생 조회 QueryDSL 구현 클래스에 stateEq 함수를 추가하여 조회 쿼리에 조건이 하나 추가하였습니다
=> 🔀 :: CREATED 상태의 STUDENT만 조회하도록 변경

src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/User.kt, src/main/kotlin/com/msg/gauth/domain/user/UserRole.kt, src/main/kotlin/com/msg/gauth/domain/user/UserRoleEntity.kt, src/main/kotlin/com/msg/gauth/domain/user/enums/UserRoleType.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptTeacherReqDto.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptUserReqDto.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptedUserRequest.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/GetMyRolesResDto.kt, src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt, src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt, src/main/kotlin/com/msg/gauth/domain/user/repository/UserRoleRepository.kt, src/main/kotlin/com/msg/gauth/domain/user/service/AcceptStudentSignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/service/AcceptTeacherSignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/service/AcceptUserSignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/service/GetAcceptedUsersService.kt, src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
회원가입 수락된 유저들을 검색 및 조회하는 기능을 개선하기 위해 UserRole Enum을 ```@ElementCollection```이 아닌 @OneToMany
User와 UserRoleType을 담고 있는 UserRole 엔티티 추가
User와 UserRole을 양방향 관계로 매핑
부모 엔티티 영속 시 자식 엔티티도 같이 영속 옵션 추가 및 부모 엔티티 삭제 시 자식엔티티도 같이 삭제 옵션 추가
UserRole Enum의 이름을 UserRoleType으로 변경하였습니다
=> 🔀 :: 232 UserRole 엔티티 추가

src/main/kotlin/com/msg/gauth/domain/user/User.kt
유저의 역할을 담은 컬렉션 테이블과 엔티티의 이름이 중복되어 엔티티 테이블이 생성되지 않는 문제가 발생했습니다
컬렉션 테이블의 이름을 roles로 변경하였습니다
이전의 pr에서 이름이 중복되는걸 깜빡하고 안바꿨었네요..
=> 🔀 :: 테이블명 중복 제거

src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
유저의 역할을 가져오는 api에서 아직 적용하지 않은 UserRole 엔티티를 사용하고 있어 아직 사용중인 collectionTable을 사용하도록 변경하였습니다
=> 🔀 :: UserRole 엔티티 대신 collection table 사용

.github/workflows/Gauth-CD.yml
- Gauth-CD 정상적으로 작동되게끔 코드를 수정하였습니다.
- Gauth-CD 정상적으로 작동되게끔 코드를 수정
- s3에 zip 파일을 업로드 하는 부분에서 error 발생. 
-> region 값은 불필요하기 때문에 삭제하였음.
- deploy 작업을 실행도중 error 발생.
->  환경변수에 저장된 region 값을 사용하도록 코드 변경. 
- 코멘트 미반영 된 부분 반영.
-> application.yml 파일은 이미 존재하므로 yml파일을 생성하는 작업을 삭제하였음.
- 모든 branch에서 CD가 작동되게끔 수정.
=> 🔀 update :: Gauth-CD 정상적으로 작동되게끔 수정

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt, src/main/resources/application.yml
prometheus로 정보를 수집하기 위한 exporter를 spirng actuator를 통해 설정해주었습니다
* spring actuator dependency 추가
* prometheus 엔드포인트를 사용하기 위한 micrometer-registry-prometheus dependency 추가
* application.yml에 health, info, prometheus 엔드포인트를 사용하기 위해서 enabled 처리 및 HTTP를 통해 내보내기 위한 설정 추가
* security config에 해당 엔드포인트들 핸들링 처리
security config에 일단 antMatchers 메서드를 통해 접근을 핸들링했는데 actuator는 처음이라 이렇게 처리하는게 맞을까 싶네요 다른 더 좋은 방법이 있다면 알려주세요!!
=> 🔀 :: 258 add exporter dependency

appspec.yml
- CodeDeploy 배포 Group 실행시 ScriptTimeOut 오류가 발생함.
- 위 문제를 해결하기 위하여 application.yml 파일에서 timeout 시간을 더 늘려주었음.
- application.yml 파일에서 timeout 시간을 변경하였음.
=> 🔀 Update :: appspec.yml

renew_jwt.go
golang으로 prometheus의 토큰을 자동으로 갱신해줄 스크립트를 작성했어요
gauth 서버에 로그인요청을 보내어 accessToken을 응답으로 받아 파일에 쓰도록 스크립트를 작성했어요
private EC2의 .bashrc에 환경변수로 ```GAUTH_SERVER_URL```, ```GAUTH_USER_NAME```, ```GAUTH_PASSWORD```추가해주어야해요
* Golang을 실행시킬 환경을 Docker로 세팅을 해보려 하는데 그냥 저희가 docker image pull을 하듯이 ec2에도 pull해서 golang을 설치하면 되는걸까요?
* jwt를 담을 파일의 접근 권한을 설정하는 것은 일단은 모든 사용자가 읽고, 쓰고, 실행할 수 있는 777로 설정해 두었는데 이건 어떻게 조정하면 좋을까요?
실행 흐름은 노션에 정리해 두었어요!! 링크는 [여기](https://www.notion.so/matsougeum/prometheus-jwt-109f2231801d48efaf4a708fc0be31a2?pvs=4)에 있어요
**아무나 Golang을 아신다면 리뷰를..**
사실 Golang이 스크립트로 실행이 잘 될지도 모르겠긴 합니다..
=> 🔀  :: golang를 사용한 accessToken 갱신 스크립트

.github/workflows/Gauth-CD.yml, .github/workflows/ci.yml
CI/CD가 작동할 떄 기준이 되는 브랜치를 변경하였습니다
CI는 main에 push 또는 모든 브랜치에서 pr이 올라왔을 경우에만 작동하도록 변경하였습니
CD는 main에 push가 일어났을 경우에만 작동하도록 변경하였습니다
CD 돌리는 도중에 자꾸 서버가 꺼지는 이유가 docker로 띄워진 redis가 꺼지는 거라면 쉘 스크립트에서 docker run gauth-redis를 한번 실행시켜 주면 문제 없는거 아닌가요?
=> 🔀 :: 266 CI/CD 기준 브랜치 변경

src/main/kotlin/com/msg/gauth/domain/client/exception/InvalidDelegateUserException.kt, src/main/kotlin/com/msg/gauth/domain/client/exception/NotValidDelegateUserException.kt, src/main/kotlin/com/msg/gauth/domain/client/service/DelegateOwnerService.kt, src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
서비스 소유자 위임하는 중에 위임자가 재학생인지 검증하는 로직을 추가했습니다.
* DelegateOwnerService 에서 검증 로직 추가
=> 🔀 :: 서비스 소유자 위임 중 재학생 검증 로직

src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
MyProfileResDto의 유저의 id 표기를 햇갈리지 않도록 userId로 변경하였습니다
=> 🔀 :: id 표기 수정

src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt, src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordUpdateRequestDto.kt, src/main/kotlin/com/msg/gauth/domain/auth/service/UpdatePasswordService.kt, src/main/kotlin/com/msg/gauth/domain/user/User.kt, src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
등록된 비밀번호를 재설정 하는 기능을 추가하였습니다.
* UpdatePasswordService 추가
* PasswordUpdateRequestDto 추가
=> 🔀 :: 비밀번호 재설정 기능 추가

src/main/kotlin/com/msg/gauth/global/config/web/WebMvcConfig.kt
> PR을 하게 된 문제상황, 배경 및 개요에 대해서 작성해주세요!
> 프론트의 버셀 url을 cors에 추가하였습니다
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
Resolves: #312
> PR에서 한 작업을 작성해주세요!
cors에서 버셀 url을 추가하였습니다
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!
=> 🔀 :: cors url 추가

src/main/kotlin/com/msg/gauth/global/config/web/WebMvcConfig.kt
> PR을 하게 된 문제상황, 배경 및 개요에 대해서 작성해주세요!
변경된 버셀 url을 cors에 적용하였습니다
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
Resolves: #314 
> cors에 버셀 url을 등록하였습니다
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!
=> 🔀 :: cors url 변경

src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptUserReqDto.kt, src/main/kotlin/com/msg/gauth/domain/user/service/AcceptUserSignUpService.kt
signUp할때 UserRole을 학생으로 고정하여 회원가입 수락 후에 UserRole이 모두 학생으로 들어가는 현상이 일어나 수정하였습니다
Resolves: #318 
> PR에서 한 작업을 작성해주세요!
회원가입 수락시에 Body로 보낸 UserRoleType을 집어넣어 최종적으로 올바른 권한이 들어가게끔 하였습니다
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!
=> 🔀 :: 회원가입 수락시에 UserRole 추가

src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt, src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpEmailVerificationService.kt, src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
회원가입을 할 때 이메일 인증을 존재하는 이메일에도 인증메일을 보내는 문제를 해결하기 위해 존재하는 이메일인지 검증한 후에 인증 메일을 보낼 수 있도록 api를 추가하였습니다
Resolves: #335 
존재하는 이메일인지 검증하는 signUpEmailVerification api를 추가하였습니다
=> 🔀 :: 회원가입시 이메일 중복 검사

src/main/kotlin/com/msg/gauth/global/thirdparty/aws/s3/S3Util.kt
Resolves: #341 
해당 취약점을 패치 후 필요없는 로직을 삭제하였습니다.
=> 프로필 파일 업로드 취약점 패치

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, src/main/kotlin/com/msg/gauth/GauthBackendApplication.kt, src/main/kotlin/com/msg/gauth/domain/admin/service/ExcelParsingService.kt, src/main/kotlin/com/msg/gauth/domain/client/presentation/dto/response/SingleClientResDto.kt, src/main/kotlin/com/msg/gauth/domain/client/service/DeleteClientService.kt, src/main/kotlin/com/msg/gauth/domain/client/service/DeleteClientsService.kt, src/main/kotlin/com/msg/gauth/domain/client/service/GetAllClientsService.kt, src/main/kotlin/com/msg/gauth/domain/client/service/RegisterClientService.kt, src/main/kotlin/com/msg/gauth/domain/client/service/UpdateAnyClientService.kt, src/main/kotlin/com/msg/gauth/domain/client/service/UpdateClientService.kt, src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/SingleAcceptedUserResDto.kt, src/main/kotlin/com/msg/gauth/domain/user/service/AcceptUserSignUpService.kt, src/main/kotlin/com/msg/gauth/domain/user/service/GetAcceptedUsersService.kt, src/main/kotlin/com/msg/gauth/global/redis/RedisCacheConfig.kt, src/main/resources/application.yml
메인 페이지의 등록된 서비스(PUBLIC) 리스트와 관리자 페이지의 유저 리스트에 레디스를 이용하여 캐시를 적용하였습니다.
등록된 서비스 캐시 적용 전
등록된 서비스 캐시 적용 후
유저 리스트 캐시 적용 전
유저 리스트 캐시 적용 후
Resolves: #346 
레디스 캐시에 대한 설정을 추가하였고 유저에 관한 캐시매니저와 서비스에 관한 캐시매니저를 따로 두어 관리하고 유저 리스트를 불러오는 api를 호출하면 캐시에 올라가고 유저 수락 api가 호출되면 올라간 캐시는 사라집니다.
서비스 캐시는 PUBLIC으로 되어있는 서비스를 반환하는 api가 호출되면 캐시에 올라가고 서비스에 관한 모든 CUD api가 호출되면 모든 엔트리는 삭제됩니다.
아직 캐시에 대한 이해도가 부족하여 감안하고 코드리뷰 부탁드립니다!
데이터베이스의 이슈로 유저에 관한 캐시 테스트를 하지 못해 pr을 확인해주시면서 브랜치로 이동해주셔서 테스트 한번만 해주시면 감사하겠습니다! 
24/9/3
유저 리스트 관한 테스트 진행 후 이상 없음을 확인하였습니다.
=> 🔀 :: 레디스 캐시 적용
